// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

let url = import.meta.env.VITE_SUPABASE_URL;
let publishableKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Fallback to local Supabase defaults if invalid or placeholder
if (!url || typeof url !== 'string' || (!url.startsWith('http://') && !url.startsWith('https://'))) {
  console.warn('Invalid or missing VITE_SUPABASE_URL. Falling back to local Supabase URL (http://127.0.0.1:54331).');
  url = 'http://127.0.0.1:54331';
}

if (!publishableKey || publishableKey === 'YOUR_ID' || publishableKey === 'YOUR ID') {
  console.warn('Invalid or missing VITE_SUPABASE_PUBLISHABLE_KEY. Using local default key.');
  publishableKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0aXp6eHJhaXFxcmZ1b29remlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE2MDAwMDAwMDAsImV4cCI6MjUwMDAwMDAwMH0.placeholder';
}

export const supabase = createClient<Database>(url, publishableKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});